language: node_js
node_js:
- '0.10'
env:
  global:
  - secure: ZNKrfXaZEWuqPqd3GGAni8T2oG9kkUdbmiq2u6tS1gLRBCbk1zaBIfpj0NZ9ibIqDVdCL18P+0VLkXqw/VQY3Taxvqz+KeN4YO2QBEIsi6dw19l0q+UosoZddhvgd+tr9QUoEALqqy3D9UtCiYacKIIgjip0rV5dPkWW0n3ZScA=
  - secure: XysO6b06yzYC3qcP+lGDwaiN/yLALMQvB1lqpSxj65oBNveiBlQka0xEMrvThr0oOX7KiYfAt7uRDJo/wTmBz0oWp3ifEgV52r0Ect0ymDojuYY1gexKLkYuKQei/24OQz0LnBhopEzao4fpUi3/RUYrnA/BN/SXDm21kGE5MKc=
